package domain

// GeneratedQuestion represents a single question generated by AI.
type GeneratedQuestion struct {
	Question string `json:"question"`
	Type     string `json:"type"`
	Marks    int    `json:"marks"`
}

// GeneratedAssignment represents the complete AI-generated assignment.
type GeneratedAssignment struct {
	Title        string              `json:"title"`
	Instructions string              `json:"instructions"`
	Questions    []GeneratedQuestion `json:"questions"`
	TotalMarks   int                 `json:"totalMarks"`
}
