package application

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/yourname/classwork/backend/internal/domain"
	"github.com/yourname/classwork/backend/internal/ports"
)

// AIServiceImpl implements the ports.AIService interface using an LLM client.
type AIServiceImpl struct {
	llmClient ports.LLMClient
}

// NewAIService creates a new instance of AIServiceImpl.
func NewAIService(llmClient ports.LLMClient) *AIServiceImpl {
	return &AIServiceImpl{
		llmClient: llmClient,
	}
}

// rawAssignmentPayload matches the JSON shape generated by the LLM.
type rawAssignmentPayload struct {
	Title        string `json:"title"`
	Instructions string `json:"instructions"`
	Questions    []struct {
		Question string `json:"question"`
		Type     string `json:"type"`
		Marks    int    `json:"marks"`
	} `json:"questions"`
	TotalMarks int `json:"total_marks"`
}

// GenerateAssignment generates an assignment based on class, subject, and prompt via LLM.
func (s *AIServiceImpl) GenerateAssignment(ctx context.Context, className, subject, prompt string) (*domain.GeneratedAssignment, error) {
	if className == "" || subject == "" || prompt == "" {
		return nil, fmt.Errorf("class, subject, and prompt are required")
	}

	if s.llmClient == nil {
		return nil, errors.New("llm client is not configured")
	}

	sysPrompt := SystemPrompt()
	usrPrompt := UserPrompt(className, subject, prompt)

	rawOutput, err := s.llmClient.Generate(ctx, sysPrompt, usrPrompt)
	if err != nil {
		return nil, fmt.Errorf("ai generation failed: %w", err)
	}

	cleanedJSON := cleanJSONOutput(rawOutput)

	var payload rawAssignmentPayload
	if err := json.Unmarshal([]byte(cleanedJSON), &payload); err != nil {
		return nil, fmt.Errorf("failed to parse AI response JSON: %w", err)
	}

	if payload.Title == "" {
		payload.Title = fmt.Sprintf("%s - %s Assignment", subject, className)
	}

	questions := make([]domain.GeneratedQuestion, 0, len(payload.Questions))
	calculatedTotalMarks := 0
	for _, q := range payload.Questions {
		marks := q.Marks
		if marks <= 0 {
			marks = 1
		}
		qType := q.Type
		if qType == "" {
			qType = "short_answer"
		}
		questions = append(questions, domain.GeneratedQuestion{
			Question: q.Question,
			Type:     qType,
			Marks:    marks,
		})
		calculatedTotalMarks += marks
	}

	totalMarks := payload.TotalMarks
	if totalMarks <= 0 || totalMarks != calculatedTotalMarks {
		totalMarks = calculatedTotalMarks
	}

	return &domain.GeneratedAssignment{
		Title:        payload.Title,
		Instructions: payload.Instructions,
		Questions:    questions,
		TotalMarks:   totalMarks,
	}, nil
}

// cleanJSONOutput strips markdown code block markers and whitespace.
func cleanJSONOutput(input string) string {
	trimmed := strings.TrimSpace(input)

	// Strip ```json ... ``` or ``` ... ```
	if strings.HasPrefix(trimmed, "```") {
		// Find end of first line
		if idx := strings.Index(trimmed, "\n"); idx != -1 {
			trimmed = trimmed[idx+1:]
		}
		if idx := strings.LastIndex(trimmed, "```"); idx != -1 {
			trimmed = trimmed[:idx]
		}
		trimmed = strings.TrimSpace(trimmed)
	}

	return trimmed
}
